In [1]:
import numpy as np

In [12]:
myList = [1,2,3,4]

In [16]:
myArray = np.array(myList)

In [4]:
myArray

array([1, 2, 3, 4])

In [11]:
myList1 = [11,12,13,14]

In [13]:
mylists = [myList, myList1]

In [14]:
mylists

[[1, 2, 3, 4], [11, 12, 13, 14]]

In [20]:
myArray = np.array(mylists)

In [21]:
myArray.shape

(2L, 4L)

In [22]:
myArray.dtype

dtype('int32')

In [23]:
myZeroArr = np.zeros(5)

In [24]:
myZeroArr

array([ 0.,  0.,  0.,  0.,  0.])

In [26]:
myZeroArr.dtype

dtype('float64')

In [33]:
oneArr =np.ones([5,5])

In [34]:
oneArr

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [35]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])