In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A  = np.random.randn(10)

In [7]:
A

array([-1.1453854 ,  0.09117374, -0.6071714 , -0.45182426, -1.80435486,
       -0.30382643,  0.10778261, -0.14755018,  1.67337385, -0.75052673])

In [8]:
B = np.random.rand(10)

In [9]:
B

array([ 0.57417939,  0.19729797,  0.94075945,  0.27235509,  0.47055452,
        0.20176578,  0.07834145,  0.96873035,  0.21850054,  0.24934189])

In [10]:
np.add(A,B)

array([-0.57120601,  0.28847171,  0.33358805, -0.17946916, -1.33380033,
       -0.10206065,  0.18612406,  0.82118017,  1.89187439, -0.50118484])

In [11]:
np.maximum(A,B)

array([ 0.57417939,  0.19729797,  0.94075945,  0.27235509,  0.47055452,
        0.20176578,  0.10778261,  0.96873035,  1.67337385,  0.24934189])

In [12]:
np.minimum(A,B)

array([-1.1453854 ,  0.09117374, -0.6071714 , -0.45182426, -1.80435486,
       -0.30382643,  0.07834145, -0.14755018,  0.21850054, -0.75052673])

In [15]:
np.random.randint(10,size=10)

array([5, 0, 6, 6, 7, 5, 7, 6, 9, 4])